coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 5%
    changes: false
    comment:
      layout: "header, diff"
      behavior: default  # update if exists else create new
